# Generated by Django 5.0.4 on 2024-04-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen_m',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='barcelona',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='label_precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='madrid',
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestionProductos.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestionProductos.producto')),
            ],
        ),
    ]
