# Generated by Django 5.0.4 on 2024-04-10 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fiesta', models.DateField(blank=True, null=True)),
                ('fecha_cita', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ubicacion_cliente', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('como_nos_conocio', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo', models.CharField(max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('razon_perdida', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedora', models.CharField(max_length=100)),
                ('es_duplicado', models.BooleanField(default=False)),
            ],
        ),
    ]
