# Generated by Django 5.0.4 on 2024-04-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='como_nos_conocio',
            field=models.CharField(choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Tiktok', 'Tiktok'), ('Instagram', 'Instagram'), ('Recomendación', 'Recomendación'), ('Google Maps', 'Google Maps'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Sin Cita', 'Sin Cita'), ('Con Cita', 'Con Cita'), ('Perdido', 'Perdido')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ubicacion_cliente',
            field=models.CharField(choices=[('Madrid', 'Madrid'), ('Valencia', 'Valencia'), ('Barcelona', 'Barcelona'), ('Videollamada', 'Videollamada')], max_length=50),
        ),
    ]
