# Generated by Django 5.0.4 on 2024-04-12 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0002_alter_cliente_como_nos_conocio_and_more'),
        ('gestionProductos', '0002_almacen_remove_producto_almacen_m_and_more'),
        ('gestionVentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ventas', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_venta', models.CharField(choices=[('En proceso', 'En proceso'), ('Completa', 'Completa'), ('Cancelada', 'Cancelada')], default='En proceso', max_length=20)),
                ('envio_entrega', models.CharField(choices=[('Envio', 'Envio'), ('Entrega', 'Entrega en tienda')], max_length=20)),
                ('tipo', models.CharField(choices=[('Alquiler', 'Alquiler'), ('Venta', 'Venta')], max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('importe_deposito', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('estado_deposito', models.CharField(choices=[('Entregado', 'Entregado'), ('Sin entregar', 'Sin entregar'), ('Devuelto', 'Devuelto')], default='Sin entregar', max_length=20)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('precio_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pendiente_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(default='En proceso', max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo_descuento', models.TextField(blank=True, null=True)),
                ('devolucion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('tiara', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_extra_fotos', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestionClientes.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='gestionProductos.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='gestionVentas.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleTransaccion',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
